### ISSUE TITLE
Not working for me plz halp I want to pwn sum random playerz

### ISSUE THREAD

**Issue by PiJoules** [jmal0/Pente#1]
I get this err:

Java Plug-in 11.31.2.13
Using JRE version 1.8.0_31-b13 Java HotSpot(TM) Client VM
User home directory = C:\Users\Pi Joules

---

c:   clear console window
f:   finalize objects on finalization queue
g:   garbage collect
h:   display this help message
l:   dump classloader list
m:   print memory usage
o:   trigger logging
q:   hide console
r:   reload policy configuration
s:   dump system and deployment properties
t:   dump thread list
v:   dump thread stack
x:   clear classloader cache
0-5: set trace level to <n>

---

**Comment by jmal0** [comment]
I know i need a jar with a trusted signature

**Comment by PiJoules** [comment]
No a good answer. Downthumb
